### ISSUE TITLE
Suggestion - Lower or fractional rates

### ISSUE THREAD

**Issue by catlinux** [azerothcore/mod-weekend-xp#28]
Good afternoon.

I am using your mod and I think it is fantastic, but I have a suggestion.

I see that you can only put whole numbers, but I would like to be able to put just 25% or a maximum of 50% more experience. Is it possible to adapt it to be able to choose values such as 1.25 or 1.5?

Thank you

**Comment by OAguinagalde** [comment]
This https://github.com/azerothcore/mod-weekend-xp/pull/30 implements those features in case you are still looking for it, it has not been merged or reviewed yet though

**Comment by poiioo** [comment]
> This #30 implements those features in case you are still looking for it, it has not been merged or reviewed yet though

Would love to see this merged!
